package structs

// defaultScalarKinds are Go types that are inexpensive to decode and should stay typed.
var defaultScalarKinds = map[string]bool{
	"string":  true,
	"bool":    true,
	"float64": true,
	"int64":   true,
	"int":     true,
}

type options struct {
	packageName   string
	extraScalars  map[string]bool
	headerComment string
	sortFields    bool
}

func (o *options) setDefaults(outputDir string) {
	if o.packageName == "" {
		o.packageName = baseName(outputDir)
	}
	if o.headerComment == "" {
		o.headerComment = "Code generated by codegen/structs; DO NOT EDIT."
	}
}

func (o *options) scalars() map[string]bool {
	if len(o.extraScalars) == 0 {
		return defaultScalarKinds
	}
	merged := make(map[string]bool, len(defaultScalarKinds)+len(o.extraScalars))
	for k, v := range defaultScalarKinds {
		merged[k] = v
	}
	for k, v := range o.extraScalars {
		merged[k] = v
	}
	return merged
}

// Option configures the Flatten generator.
type Option func(*options)

// WithPackageName sets the Go package name for generated files.
// Default: basename of the output directory.
func WithPackageName(name string) Option {
	return func(o *options) { o.packageName = name }
}

// WithExtraScalars adds type names that should be treated as scalars
// (kept typed) in addition to the built-in set (string, bool, float64, int64, int).
func WithExtraScalars(names ...string) Option {
	return func(o *options) {
		if o.extraScalars == nil {
			o.extraScalars = make(map[string]bool, len(names))
		}
		for _, n := range names {
			o.extraScalars[n] = true
		}
	}
}

// WithHeaderComment overrides the default "DO NOT EDIT" header comment.
func WithHeaderComment(comment string) Option {
	return func(o *options) { o.headerComment = comment }
}

// WithSortFields sorts generated fields: primary key fields (named "ID")
// first, then alphabetically by name. ExtraFields always come before
// source fields, preserving their original order.
func WithSortFields() Option {
	return func(o *options) { o.sortFields = true }
}
