// Code generated by codegen; DO NOT EDIT.
package {{.PackageName}}

import (
    {{- range .Imports }}
    "{{ . }}"
    {{- end }}
)

{{ range .Clients }}
//go:generate mockgen -package=mocks -destination=../mocks/{{$.PackageName}}.go -source={{$.PackageName}}.go {{.Name}}
type {{.Name}} interface {
    {{- range $sig := .Signatures }}
    {{ $sig }}
    {{- end }}
}
{{ end }}